#!/usr/bin/env bash

#tentative de correction

export PYTHONPATH="${PYTHONPATH}:$(pwd)"

ME_MYSQL_USER=melani_dev ME_MYSQL_PWD=Mel0ni_dev_123 ME_MYSQL_HOST=localhost ME_MYSQL_DB=ME_db ME_MYSQL_PORT=5000


if [ "$1" = "console" ];then
    ME_MYSQL_USER=melani_dev ME_MYSQL_PWD=Mel0ni_dev_123 ME_MYSQL_HOST=localhost ME_MYSQL_DB=ME_db ME_MYSQL_PORT=5000 ./console.py
else
    ME_MYSQL_USER=melani_dev ME_MYSQL_PWD=Mel0ni_dev_123 ME_MYSQL_HOST=localhost ME_MYSQL_DB=ME_db ME_MYSQL_PORT=5000 ./api/v1/app.py
fi